# Site settings
title: Billistrations
email: billyoreilly@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
# url: "http://billistrations.com/"
twitter_username: billistrations
github_username:  GillytheGit

# Build settings
markdown: kramdown
include: ["work"]
exclude: [node_modules, bower_components, Gruntfile.coffee, package.json, bower.json ]

# Build settings
sass:
    sass_dir: _sass
    style: :compressed